version: '3'
services:
  db:
    ports:
      - 5433:5432
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: root
      POSTGRES_DB: personalBlog_DB
